name: Continuos test

on: pull_request

jobs:
    continuos-integration:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Install NodeJs
          uses: actions/setup-node@v3
          with:
           node-version: '^20'

        - name: Grat execute permissions for Jest
          run: chmod +x ./node_modules/.bin/jest

        - name: run install and test
          run: |
            npm install
            npm test 